export const SUBSCRIPTION_LIMITS = {
  FREE: {
    TRAINING_PLANS: 2,
    FAVOURITE_WORKOUTS: 8,
    FAVOURITE_FOLDERS: 2,
  },
  PREMIUM: {
    TRAINING_PLANS: 999,
    FAVOURITE_WORKOUTS: 999,
    FAVOURITE_FOLDERS: 999,
  },
} as const
