export const SUBSCRIPTION_LIMITS = {
  FREE: {
    TRAINING_PLANS: 2,
    FAVOURITE_WORKOUTS: 8,
    FAVOURITE_FOLDERS: 2,
  },
  PREMIUM: {
    TRAINING_PLANS: 30,
    FAVOURITE_WORKOUTS: 50,
    FAVOURITE_FOLDERS: 20,
  },
} as const
